### ISSUE TITLE
Allow clients to pass in any READ-able…

### ISSUE THREAD

**Issue by bwinton** [agersant/mp3-duration#1]
In particular, I'd like to pass in a [reqwest::Response](https://docs.rs/reqwest/0.8.5/reqwest/struct.Response.html) object, which implements `Read`, instead of writing it to a file, calling `from_file`, then deleting the file… 🙂

I'm not very advanced at Rust, but I _think_ you would just need to add `pub` to the [`from_read` function](https://github.com/agersant/mp3-duration/blob/master/src/lib.rs#L121)…

**Comment by bwinton** [comment]
(I guess the other thing that would work for me, is to read the response into a `Vec<u8>` and pass that, if you would rather that kind of API…)

**Comment by agersant** [comment]
I'm happy with exposing from_read. 

Added in ca062d6ad4117f6411ad8e39df4e4af297d52559 and published on crates.io as v0.1.2.

**Comment by bwinton** [comment]
Just tested it, and it works wonderfully! Thank you! 😄
