### ISSUE TITLE
MP3DurationError is effectively private

### ISSUE THREAD

**Issue by compenguy** [agersant/mp3-duration#11]
In error.rs, MP3DurationError is declared public, but the module that contains it is private, so external crates are unable to reference the MP3DurationError type:
```
error[E0603]: module `error` is private
   --> src/errors.rs:163:32
    |
163 |     fn from(err: mp3_duration::error::MP3DurationError) -> Self {
    |
```

Either the error module should be made public, or the MP3DurationError type should be re-exported from lib.rs.

**Comment by agersant** [comment]
Thank you for the report. That is not intentional, I would welcome a PR to fix this.
(otherwise I will get to it but no idea when)
