### ISSUE TITLE
Length of file not determined

### ISSUE THREAD

**Issue by chrisheib** [agersant/mp3-duration#16]
File: https://workupload.com/file/aUnRyjrBfWY

`
    let duration = mp3_duration::from_path(&path).unwrap_or_default();
    duration.as_secs()
`

returns 0. Expected time is around 5:40, or 340 seconds. 

I guess because the bitrate is set to 0 initially or some shenanigans. 

Any idea on how to fix this?

**Comment by agersant** [comment]
I looked into this and found the file is misencoded. This is the start of its XING header:
![image](https://user-images.githubusercontent.com/817256/111052091-db616800-840c-11eb-8fee-5236854ee0e7.png)

The `58 69 6E 67` sequence is the `Xing` identifier. The flags field is set to `0x07`, which indicates that the rest of the XING header contains the number of frames, number of bytes and TOC (table of content) fields. The next four bytes are all `0x00`, which means the file is described as containing 0 frames of audio data - and thus having a duration of 0 seconds. [Readable spec](https://www.codeproject.com/Articles/8295/MPEG-Audio-Frame-Header#XINGHeader).

If you want to fix this specific file, you can open it in Foobar2000 (which also cannot read the expected duration) and `Right Click` ->
`Utilities` -> `Fix VBR MP3 header…`. The file then correctly shows up as 342s. Other tagging programs usually have similar options too.
