### ISSUE TITLE
Handling APE tags

### ISSUE THREAD

**Issue by mqus** [agersant/mp3-duration#6]
Hi! 

Thanks for creating this library and doing it properly (e.g. not "estimating" the length but really measuring it)!

There were some files in my collection which tripped up however, with the error:
`Unexpected frame, header: 1095779668 `
In hex thats 0x41504554, which can be read as APET. This points to APE-Tags in the file (https://en.wikipedia.org/wiki/APE_tag). Until today I didn't even know that these could be inside of mp3 files, but I would really appreciate it if you could add some code to skip these.

**Comment by agersant** [comment]
Thank you for the report!

Can you email me one of the files causing issues at antoine.gersant@lesforges.org (or upload it somewhere)?

**Comment by mqus** [comment]
I already have a patch for this (is ready now), should I send the file to you anyway?

**Comment by agersant** [comment]
Thanks a lot for going through the effort of writing the fix <3
I posted a couple minor requests on the PR and then we're good to go.

**Comment by agersant** [comment]
Published on crates.io as v0.1.5

**Comment by mqus** [comment]
thanks!
